


--create database radimopetprvo;

--drop database radimopetprvo;

--se radimopetprvo; 

--create table smjerovi (
--sifra int,
--naziv varchar(50),
--trajanje int,
--cijena decimal (18,2),
--vaucer bit
--);

--create table grupe(
--sifra int,
--naziv varchar(5),
--smjer int,
--datumpocetka datetime,
--maxpolaznika int,
--predavac int,
--);

--create table polaznici (
--sifra int,
--ime varchar (50),
--prezime varchar (50),
--email varchar (100),
--oib char (11),
--brojugovora varchar (10),
--);

--create table predavaci (
--sifra int,
--ime varchar (50),
--prezime varchar (50),
--email varchar (100),
--oib char (11),
--iban varchar (50),
--);

--create table clanovi (
--grupa int,
--polaznik int,

--);
